
        "# bus reservation system\n",
        
        "print(\"*****-#--  WELCOME TO BUS RESERVATION SYSTEM -#--*****\")\n",
        "total_seat=20\n",
        "booked=[]\n",
        "while True:\n",
        " print(\"1 show seats\")\n",
        " print(\"2 booked seats\")\n",
        " print(\"3 cancle seats\")\n",
        " print(\"4 exit\")\n",
        "\n",
        "# for view seat\n",
        "\n",
        " choice=int(input(\"enter the choice\"))\n",
        " if choice==1:\n",
        "  print(\"-------  SEAT STATUS  -------\")\n",
        "  for i in range (1,total_seat+1):\n",
        "   if i in booked:\n",
        "     print(\"seat\",i,\"booked\")\n",
        "   else:\n",
        "    print(\"seat empty\")\n",
        "\n",
        "#for booked seats\n",
        "\n",
        " elif choice==2:\n",
        "  seat=int(input(\"enter the seat no number you want to book\"))\n",
        "  if seat < 1 or seat > total_seat:\n",
        "    print(\"!!!!!!  INVALID SEAT NUMBER  !!!!!!\")\n",
        "  elif seat in booked:\n",
        "    print(\"-!!------  SEAT ALREADY BOOKED  ------!!-\")\n",
        "  else:\n",
        "    booked.append(seat)\n",
        "    print(\"######  BOOK SUCCESSFULLY  ######\")\n",
        "\n",
        "\n",
        "# for cancel seat\n",
        " elif choice==3:\n",
        "    seat=int(input(\"enter the seat no for cancel\"))\n",
        "    if seat<1 or seat > total_seat:\n",
        "      print(\"!!!!!!  INVALID NUMBER   !!!!!!\")\n",
        "    elif  seat in booked:\n",
        "      booked.remove(seat)\n",
        "      print(\"#### CANCEL SUCCESSFULLY ####\")\n",
        "    else:\n",
        "      print(\"!!!!!!  SEAT IS NOT BOOKED  !!!!!!\")\n",
        "\n",
        "#exit\n",
        " elif choice==4:\n",
        "    print(\"###### THANKYOU ######\")\n",
        "    break\n",
        " else:\n",
        "    print(\"!!!!!!  INVALID CHOICE  !!!!!!\")\n",
     
  
